### PR TITLE
Update sample app for Release ADOT nodejs Lambda layer aws-otel-nodej…

### PR DESCRIPTION
**Pull request by willarmiros**
…s-ver-0-24-0 and python38 Lambda Layer aws-otel-python38-ver-1-5-0

### CODE REVIEW

**Review by NathanielRN — COMMENTED** [review]
I think we also need to update the Layer ARNs in `sample-apps/python-aws-sdk-aiohttp-sam/template.yml`?

https://github.com/aws-observability/aws-otel-lambda/blob/b82bb9306f3fcbc1e77ea356778fdc93b3451968/sample-apps/python-aws-sdk-aiohttp-sam/template.yml#L40

**Comment by willarmiros** [comment]
@NathanielRN good catch! Just updated

**Comment by NathanielRN** [comment]
Will we have a separate PR for the collector release like we did for #115 and #116? My opinion is that we should combine all the Lambda Layer updates in this 1 PR.

Right now it’s still pointing to `0.29.1`.

https://github.com/aws-observability/aws-otel-lambda/blob/b82bb9306f3fcbc1e77ea356778fdc93b3451968/sample-apps/dotnet-wrapper-aws-sdk-terraform/layer.tf#L3

Also, do we have a new release for the collector? I saw there’s one published as `0.12.0` from [this release workflow](https://github.com/aws-observability/aws-otel-lambda/actions/runs/1185027253) but should that be `0.30.0`? For example, [here is the release workflow for collector 0.29.1](https://github.com/aws-observability/aws-otel-lambda/actions/runs/1009394264).

Finally, I also noticed [this workflow to publish a Lambda Layer for Java Wrapper 1-5-0:2](https://github.com/aws-observability/aws-otel-lambda/actions/runs/1184933764), do we want to update the sample apps to use it like we did in #116?

**Comment by willarmiros** [comment]
@NathanielRN we did do a 0.12.0 release for the Collector layer, but I realized I named it using `0-12-0`, the downstream ADOT collector version, instead of the upstream `0-33-0` version, so discussing with @wangzlei if we should re-release a rename layer. If we do release the renamed layer, we'll probably include the changes in this PR.

The Java layer updates were done separately because there were problems with the canary tests for Java Agent and Wrapper - so we wanted to independently verify those were fixed before updating the other layers.

**Review by wangzlei — APPROVED** [review]

**Pull request merged**
